title = "AWS Modernization with Spinnaker"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "true"
defaultContentLanguage = "ko"
uglyurls = "true"
enableEmoji = true
baseURL = "/"

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "Young-ook"
  # Description of the site, will be used in meta information
  description = "AWS Modernization with Spinnaker"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]
weight = 11

[languages]
[languages.ko]
languageName = "한국어"
languageCode = "ko-kr"
title = "Well-Architected Containers with DevOps"
weight = 1

[[languages.ko.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> AWS 빌더스 라이브러리"
url = "https://aws.amazon.com/builders-library/"
weight = 11

[[languages.ko.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> 카오스 엔지니어링"
url = "https://catalog.us-east-1.prod.workshops.aws/workshops/7379e94f-6981-4dd8-bb46-8ec4aff3a825/en-US"
weight = 11

[languages.en]
languageName = "English"
languageCode = "en-us"
title = "Well-Architected Containers with DevOps"
weight = 2

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> AWS Builders Library"
url = "https://aws.amazon.com/builders-library/"
weight = 11

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Chaos Engineering"
url = "https://catalog.us-east-1.prod.workshops.aws/workshops/7379e94f-6981-4dd8-bb46-8ec4aff3a825/en-US"
weight = 11

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true
